global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'All Monitoring'
    static_configs:
      - targets: ['localhost:9100','CLIENT-1:9100','CLIENT-2:9100','CLIENT-3:9100']